name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      playwright:
        image: mcr.microsoft.com/playwright:focal
        options: --entrypoint npm
   
    steps:
    - uses: actions/checkout@v3
   
    - name: Install dependencies
      run: npm ci
    - name: Run Cucumber tests
      run: npm test
    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Report
        path: test-results
        retention-days: 2
